# Generated by Django 3.0.4 on 2020-03-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_id', models.CharField(default='', max_length=30, verbose_name='compound_id')),
                ('smiles', models.CharField(default='', max_length=180, verbose_name='smiles')),
            ],
        ),
    ]
